### PR TITLE
338_counting_bits.cpp addded in c++

### PR DESCRIPTION
**Pull request by Saurabh-Dadhich**
Solution to leetcode problem counting_bits is added in c++.
 issue no - #606

### CODE REVIEW

**Comment by noisefilter19** [comment]
What's happening here? @Saurabh-Dadhich 
3 Files!!

**Review by noisefilter19 — CHANGES_REQUESTED** [review]
I don't understand the point of this PR

**Comment by Saurabh-Dadhich** [comment]
@noisefilter19 I am facing problem in cloning repo, let me try one more time.

**Comment by noisefilter19** [comment]
Hey @Saurabh-Dadhich please don't make changes to other files. You could have raised an issue or highlighted it in a comment. 
Anyways, I believe the problem is now solved

**Comment by Saurabh-Dadhich** [comment]
hey @noisefilter19  I have again send you new pull request #742, please review it and sorry for misunderstanding

**Pull request closed without merging**
