### PR TITLE
Added Solution for shortest common supersequence

### PR DESCRIPTION
**Pull request by SuryankDixit**
This problem falls under the category of Dynamic Programming and a variation of longest common sub-sequence.

### CODE REVIEW

**Comment by SuryankDixit** [comment]
@noisefilter19  Can you please review this?

**Comment by noisefilter19** [comment]
@SuryankDixit Have you read the Contributing Guidelines? I don't think so. You haven't been assigned an issue. Neither is this a Leetcode problem.
Please don't spam PRs to gain a Tshirt

**Comment by SuryankDixit** [comment]
@noisefilter19 Sorry for the inconvenience caused to you but I think there is a misunderstanding here on my behalf. I was assigned this pull request #589 . But due to some bad commits in my forked repo, I messed up with it in first place. So I had to delete that and re-forked this repository. And I think due to this, the original pull request got deleted as well.

Secondly this is a Leetcode problem number 1092. Refer This: [(https://leetcode.com/problems/shortest-common-supersequence/)]
Maybe not all the wrong PR's are spam, some might be genuine mistake.

**Comment by SuryankDixit** [comment]
@noisefilter19 I got Pull Request #589 
Here is the link: [https://github.com/noisefilter19/LeetCode_Algorithms/issues/589](url)

**Pull request closed without merging**
