### PR TITLE
feat: add multiply strings algorithm using javascript

### LINKED ISSUE #920: 43 | Multiply Strings | Javascript
Problem name: Multiply Strings
Difficulty: Medium
Language: Javascript

### PR DESCRIPTION
**Pull request by Koddi-Evangelista**
Closes #920

### CODE REVIEW

**Comment by suburban-daredevil** [comment]
Hey @Koddi-Evangelista . I am a first time contributor to this repository. Can you please clarify whether I will be able to link a PR to an issue like you have done or do I need write permissions for that?

**Comment by Koddi-Evangelista** [comment]
> Hey @Koddi-Evangelista . I am a first time contributor to this repository. Can you please clarify whether I will be able to link a PR to an issue like you have done or do I need write permissions for that?

Hey folk! you didn't need a write permission just do what I did

**Comment by suburban-daredevil** [comment]
Okay. But I cannot find out how to do that. Can you please guide me? @Koddi-Evangelista

**Comment by Koddi-Evangelista** [comment]
> Okay. But I cannot find out how to do that. Can you please guide me? @Koddi-Evangelista

here is the link: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

you just need to put your preferred keyword plus the issue number to the pull request description/body.
for example in my case, I wrote Closes #920

**Comment by suburban-daredevil** [comment]
Thank you very much @Koddi-Evangelista . It worked!

**Pull request merged**
