### PR TITLE
Add Python solution for problem #869

### PR DESCRIPTION
**Pull request by conradojordan**
Add the solution to problem number 869 using Python3

### CODE REVIEW

**Comment by conradojordan** [comment]
Solves issue #180

**Comment by conradojordan** [comment]
Closes #180

**Comment by conradojordan** [comment]
I'm not sure if I linked the issue correctly, let me know if I did anything wrong so I can fix it. Thanks!

**Review by noisefilter19 — APPROVED** [review]

**Comment by noisefilter19** [comment]
No problem. Thanks for contributing

**Pull request merged**
