### PR TITLE
Dictionary Attack implementation in Python

### PR DESCRIPTION
**Pull request by atshaya-anand**
#306 Have made the PR. Please merge this!

### CODE REVIEW

**Comment by noisefilter19** [comment]
Is this a leetcode problem?

**Comment by noisefilter19** [comment]
If so add the link, if not I can't merge this into the repo

**Comment by atshaya-anand** [comment]
I think this is not a leetcode problem, this is an implementation of an algorithm in Python. If you feel this cannot be added into your repo, then i'll try some other problem

**Comment by noisefilter19** [comment]
This repo as the name suggests is specifically for Leetcode problems and this doesnt seem like one

**Pull request closed without merging**
