### PR TITLE
Create Minimum_Deletion_Cost_to_Avoid_Repeating_Letters.cpp

### PR DESCRIPTION
**Pull request by su-madeye**
The following PR contains the cpp solution to the problem Minimum Deletion Cost to Avoid Repeating Letters found on leetcode.

### CODE REVIEW

**Comment by noisefilter19** [comment]
@su-madeye Please open an issue wrt this PR and then wait for assignment as it eases the task of tracking solutions. You may reopen the PR after that

**Comment by su-madeye** [comment]
I think that you have misunderstood. I raised a issue before hand #30.
https://github.com/noisefilter19/LeetCode_Algorithms/issues/30

**Comment by noisefilter19** [comment]
You should've waited for the assignment. It results in confusion. Anyways , it's fine

**Review by noisefilter19 — APPROVED** [review]

**Comment by su-madeye** [comment]
Sorry and Thanx.

**Pull request merged**
