### PR TITLE
Added Code for Increasing Triplet Subsequence

### LINKED ISSUE #68: 334 | Increasing Triplet Subsequence | Python
Problem name: Increasing Triplet Subsequence
Difficulty: Medium
Language: Python

### PR DESCRIPTION
**Pull request by sark-2110**
Added Code for Increasing Triplet Subsequence in Python fixes #68

### CODE REVIEW

**Review by noisefilter19 — APPROVED** [review]

**Comment by noisefilter19** [comment]
Hey @SaimantikaBasu , you mentioned that you can help with maintenance of the repo

**Comment by noisefilter19** [comment]
Hey @sark-2110, you mentioned that you'd be interested in maintaining the repo

**Comment by sark-2110** [comment]
@noisefilter19 Yes I am interested

**Comment by noisefilter19** [comment]
Cool. I'd be adding you as a collaborator. A few things to take care of:
1) Check the profile of a user before assigning him the issues. (Avoid assigning issues to users who have very recently joined, they might be fake profiles just to get hacktoberfest swag)
2) People who are first time contributors can be given priority instead of the same users who raise issues
3) Contributing.md needs to be followed everytime. You can close spam PR's or those which do not follow the criteria

Let me know if you're in and I'll add u ASAP

**Comment by sark-2110** [comment]
I will follow the guidelines .you can count me in

**Comment by noisefilter19** [comment]
Cool. Added you as a collaborator

**Pull request merged**
