### PR TITLE
Added code | Single Element in Sorted Array and First and Last position of an element in a sorted array | Python | Resolves #894 and #891

### LINKED ISSUE #891: 34 | Find First and Last Position of Element in Sorted Array | Python
Problem name: Find First and Last Position of Element in Sorted Array
Difficulty: Medium
Language: Python

### LINKED ISSUE #894: 540 | Single Element in a Sorted Array | Python
Problem name: Single Element in a Sorted Array
Difficulty: Medium
Language: Python

### PR DESCRIPTION
**Pull request by suburban-daredevil**
Closes #894
Closes #891

Problem: Single Element in a Sorted Array
Number: 540
Language: Python

Problem: First and Last position of an element in a sorted array
Number: 34
Language: Python

Added code for these problems in this PR.

### CODE REVIEW

**Comment by suburban-daredevil** [comment]
Hey @noisefilter19. This PR solves the issue #894 .Thanks!

**Comment by suburban-daredevil** [comment]
Hey @noisefilter19 . I am a first time contributor to this repository and I think I don't have the write permission to manually link up PR to an issue. Hence I have tagged the issue number which was assigned to me in the previous comment. Hope you will notice that. Thanks!

**Comment by suburban-daredevil** [comment]
closes #894

**Comment by suburban-daredevil** [comment]
Closes #894

**Comment by suburban-daredevil** [comment]
Hey @noisefilter19 . I have updated the PR to solve 2 issues that were assigned to me. I am not bothered about the number of PR's actually but their quality. Hope they are correct and incase of any corrections or rectifications I'm happy to modify as well. Thanks!

**Comment by suburban-daredevil** [comment]
Hey @noisefilter19 . Can you please provide workflow approval to test the PR? Thanks!

**Comment by suburban-daredevil** [comment]
He @noisefilter19 . Can you please assign this issue #958 to me? I would like to contribute

**Review by noisefilter19 — APPROVED** [review]

**Pull request merged**
