### PR TITLE
Add solution for zigzag conversion in Golang

### PR DESCRIPTION
**Pull request by amanjain97**
## WHAT
Added solution for zigzag conversion in Golang 

## WHY
Resolves https://github.com/noisefilter19/LeetCode_Algorithms/issues/8

## PROBLEM LINK
https://leetcode.com/problems/zigzag-conversion

### CODE REVIEW

**Review by noisefilter19 — CHANGES_REQUESTED** [review]
Please add the problem link as well as a comment

**Comment by amanjain97** [comment]
@noisefilter19 Added.

**Comment by amanjain97** [comment]
https://leetcode.com/problems/zigzag-conversion

**Comment by noisefilter19** [comment]
Oops, I meant in the solution within the file

**Comment by amanjain97** [comment]
Added comments.

**Review by noisefilter19 — APPROVED** [review]

**Pull request merged**
